optimization_settings:
    MinSum.budget-10.adaptive:
        criterion: MinSum
        budget: 10
        max_solving_time: 3600
        simulation_config: cells-config.yaml
        cells_populations_file: results/cell-populations.csv
        approximate_vaccine_element_scores: "results/vaccine-elements.scores.{}.rep-{}.csv"
        distance_from_self_scores: null
        distance_from_self_column: null
        weight_column: null
        peptides_file: peptide-sequences.csv
        peptide_sequence_column: Mut_peptide
        out: results/selected-vaccine-elements.budget-10.minsum.adaptive.csv
        vaccine_out: results/vaccine.budget-10.minsum.adaptive.csv
        p_response_factor: null
        vaccine_elements: mutations
        mutation_id_column: Mutation_ID
