min_hotspot_uses: 1

hue_order:
    - 1000-cells.10x
    - 10000-cells.10x

simulation_settings:
    MinSum.budget-10.adaptive:
        selected_peptides: ./analysis/vaccines/selected-vaccine-elements.budget-10.minsum.adaptive.csv
        bar_chart: "./analysis/vaccines/bar-chart.budget-10.minsum.adaptive.png"
