simulations : ./analysis/cell/cell-populations.csv
scores : "./analysis/approximate_scores/vaccine-elements.scores.{}.rep-{}.csv"

final_response_out : ./analysis/evaluation/final-response-likelihoods.csv
sim_specific_response_out : ./analysis/evaluation/sim-specific-response-likelihoods.csv
box_plot_out : ./analysis/evaluation/plots/global/box-plot.png
violin_plot_out : ./analysis/evaluation/plots/global/violin-plot.png
bar_plot_out : ./analysis/evaluation/plots/global/bar-plot.png
line_plot_out : ./analysis/evaluation/plots/global/line-plot.png
sim_specific_line_plot_out : "./analysis/evaluation/plots/specific/line-plot.{}.{}.png"

final_vaccines:
    MinSum.budget-10.adaptive: ./analysis/vaccines/vaccine.budget-10.minsum.adaptive.csv

sim_specific_vaccines:
    MinSum.budget-10.adaptive: ./analysis/vaccines/selected-vaccine-elements.budget-10.minsum.adaptive.csv

population_sizes:
    1000-cells.10x: 1000
    10000-cells.10x: 10000
